"""Regression suite for the /triangulate skill.

Locks in canonical player verdicts and the structural invariants of
`scripts.xfp.lib.triangulate_core.triangulate_player`. The expected
values were generated by running the engine on 2026-05-30 against the
production projection + archetype panels.

Failures here mean either:
  (a) the engine's synthesize() / apply_overrides() logic shifted —
      investigate intentionality before "fixing" the test;
  (b) the underlying projection / archetype data drifted enough to
      flip a borderline verdict — update the expected value with a
      note in the commit message;
  (c) a real bug was just exposed — fix the engine, not the test.
"""
from __future__ import annotations

import sys
from pathlib import Path

# The repo's pyproject sets pythonpath = ["src"], but triangulate_core
# lives at scripts/xfp/lib. Ensure the repo root is importable so
# `from scripts.xfp.lib.triangulate_core import ...` resolves.
_REPO_ROOT = Path(__file__).resolve().parent.parent
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

import pytest

from scripts.xfp.lib.triangulate_core import (
    triangulate_player,
    consolidate_verdict,
    apply_overrides,
    _VERDICT_MAP,
)
from scripts.xfp.lib.cached_data import _load_projection


# (name, expected_verdict_substring_or_None, expected_bucket,
#  expected_verdict_top_or_None, expected_override_tag_or_None)
#
# Substrings use the literal em-dash character emitted by the engine so
# we don't have to care whether the running shell is cp1252 or utf-8.
CANONICAL_CASES = [
    # 2026-06-14 refresh. TWO categories of update this pass:
    #  (1) INTENTIONAL — Ryan Weathers now downgrades to 'CAUTION — decline veto'
    #      via the new SP velo-decline veto (SEVERE velo fade vetoes a marcel_il
    #      'archetype breakout' BUY). See sp_decline_model.decline_lens_map() +
    #      apply_overrides DECLINE_VETO + velo_signal_2026-06-13.md.
    #  (2) PRE-EXISTING DATA DRIFT (independent of the velo work; flagged in
    #      memory obs #386 on 2026-06-11) — Judge, Detmers, Suárez, Schmitt,
    #      Turner drifted with rh3/rp3 + PL + archetype data since the 06-06
    #      fixture. The velo veto is SP+BUY+SEVERE/DECLINE-RISK only, so it
    #      cannot touch the four hitters, and Detmers came through as a
    #      (correctly) non-vetoed BUY. Refreshed per the docstring's option (b).
    #      NOTE: Judge STRONG HOLD -> MIXED is a meaningful drift worth a look.
    #  2026-06-17 (option b) — the rp3 coverage fix moved recently-pitched
    #      starters from suppressed marcel_il priors to real data_driven reads
    #      (Detmers 7.77 -> 11.84, etc.). Detmers stays BUY but the sub-reason
    #      shifts archetype-breakout -> process-upgrade; Weathers' base read is
    #      now MIXED, so he no longer qualifies for the SP+BUY+SEVERE decline
    #      veto (the velo concern now reads as MIXED, not CAUTION). Schmitt
    #      (hitter, independent rh3/PL drift) flips BUY -> MIXED.
    # On the 60-day IL (2026-06): PL-unranked + elite model/archetype would read
    # as a naked BUY, so the engine caveats it. Verdict-top intentionally not
    # locked for an injured player (talent-only, secondary). See _CANONICAL_IL.
    ("Aaron Judge",     "ON IL",                   "H",  None,      "IL"),
    ("Reid Detmers",    "BUY — process upgrade",   "SP", "BUY",     None),
    ("Ryan Weathers",   "MIXED — see profile",     "SP", "MIXED",   None),
    # Ryne Nelson straddles the PL Top-100 boundary: when PL-ranked with a big model
    # gap he's FADE (pl_outcome_chase); once he drops OFF the board (Wk14: pl='—',
    # model #133, archetype OVR 36 TRENDING_DOWN) the gap rule can't fire and he reads
    # CAUTION (process_red_flag) instead — equally bearish, different bucket. The verdict
    # flips FADE↔CAUTION as he enters/exits the Top 100, so this is a bucket-only lock.
    ("Ryne Nelson",     None,                     "SP", None,      None),
    # 2026-06-19 PL cache refresh (Wk12 hitters, Wk13 SPs): fresh ranks flipped
    #   these off MIXED. Suárez/Turner now PL-ranked well above model -> FADE (PL
    #   chasing outcomes); Schmitt's archetype-breakout rule fires with the fresh
    #   PL rank + model lag. Data-driven (cache refresh), not a code change.
    ("Eugenio Suárez",   "FADE — PL chasing outcomes", "H",  "FADE",  None),
    # 2026-06-20 refresh: Schmitt's BUY sub-reason drifted archetype-breakout ->
    #   process-upgrade (rh3/archetype data shift; still BUY top). Data-driven.
    ("Casey Schmitt",   "BUY — process upgrade",      "H",  "BUY",   None),
    ("Bailey Ober",     "CAUTION",                "SP", "CAUTION", None),
    ("Bryan Woo",       "HOLD — process intact",   "SP", "HOLD",    "PROCESS_INTACT"),
    ("Kyle Bradish",    "HOLD — post-TJ ramp",     "SP", "HOLD",    "POST_TJ_RAMP"),
    # Trea Turner sits ON the FADE/MIXED boundary: the FADE rule needs model−PL
    # gap > 60, and his gap swings across 60 with small model-rank moves on each
    # data refresh (2026-06-19 gap 86 → FADE; 2026-06-22 statcast/archetype rebuild
    # model #120, gap 41 → MIXED). Archetype OVERALL stays 42 / TRENDING_DOWN either
    # way. Locking a boundary verdict invites data-driven flip-flops, so this is a
    # bucket-only lock — resolution + H bucket stay enforced.
    ("Trea Turner",     None,                      "H",  None,    None),
    ("Framber Valdez",  "CAUTION",                "SP", "CAUTION", None),
    # Bucket-only locks (verdict varies, just confirm resolution + bucket):
    ("Jhoan Duran",     None,                     "RP", None,      None),
]


@pytest.fixture(scope="module")
def _warm_cache():
    """Force the engine's lru_cache to populate once before timing tests."""
    triangulate_player("Aaron Judge")
    yield


# Injured canonical players have their ESPN IL status injected (deterministic +
# PL-independent) — sourced AUTOMATICALLY from the injury_status cache the daily
# pipeline refreshes, so no hand-maintained list goes stale.
from scripts.xfp.lib.injury_status import il_status_for as _il_status_for

# PL-cache staleness windows (days) — mirror pl_cache._warn_stale_caches.
_PL_STALE_DAYS = {'H': 7, 'SP': 7, 'RP': 7}


def _pl_cache_age_days(bucket: str):
    """Days since the PL Top-N cache for this bucket was fetched, or None."""
    import json
    import datetime
    from scripts.xfp.lib.pl_cache import PL_CACHE_FILES
    try:
        from plv_clone.paths import RESEARCH
        path = RESEARCH / 'pl_cache' / PL_CACHE_FILES[bucket]
        with open(path, encoding='utf-8') as fh:
            fetched = json.load(fh).get('fetched')
        if not fetched:
            return None
        return (datetime.date.today() - datetime.date.fromisoformat(fetched)).days
    except Exception:
        return None


@pytest.mark.parametrize(
    "name,verdict_sub,bucket,verdict_top,override_tag",
    CANONICAL_CASES,
    ids=[c[0] for c in CANONICAL_CASES],
)
def test_canonical_player(name, verdict_sub, bucket, verdict_top, override_tag, _warm_cache):
    il = _il_status_for(name)   # from the injury_status cache (auto-refreshed)
    result = triangulate_player(name, il_status=il)
    assert result is not None, f"{name!r} failed to resolve"
    assert result["bucket"] == bucket, (
        f"{name!r} bucket={result['bucket']!r}, expected {bucket!r}"
    )
    # Canonical verdicts depend on the weekly PL Top-N cache. When that cache is
    # STALE and this player is consequently unranked (pl_main UR/—), the verdict
    # can flip on operational data staleness rather than a code change. Relax the
    # lock (xfail) rather than red-CI — refresh PL Top 150 to re-engage it. A
    # genuine code regression with a FRESH cache still fails hard, and a
    # fresh-cache UR still enforces. Resolution + bucket above are always locked.
    # Injured players (il set) are PL-independent — the IL caveat dominates — so
    # they skip the freshness relaxation and stay locked.
    if il is None:
        _age = _pl_cache_age_days(bucket)
        if (_age is not None and _age > _PL_STALE_DAYS.get(bucket, 7)
                and result.get("pl_main") in ("UR", "—")):
            pytest.xfail(
                f"{name}: PL {bucket} cache {_age}d stale -> pl_main={result.get('pl_main')!r}; "
                f"refresh PL Top 150 to re-enforce the verdict lock.")
    if verdict_sub is not None:
        assert verdict_sub in result["verdict"], (
            f"{name!r} verdict={result['verdict']!r} did not contain {verdict_sub!r}"
        )
    if verdict_top is not None:
        assert result["verdict_top"] == verdict_top, (
            f"{name!r} verdict_top={result['verdict_top']!r}, expected {verdict_top!r}"
        )
    # override_tag asserted only when we have a strong expectation.
    # For None expectations we still check it's None — non-overridden
    # verdicts should never carry a tag.
    assert result["override_tag"] == override_tag, (
        f"{name!r} override_tag={result['override_tag']!r}, expected {override_tag!r}"
    )


# --------------------------------------------------------------------
# Structural / invariant tests
# --------------------------------------------------------------------

def test_il_caveat_helper():
    """The pure IL-marker helper: IL states -> caveat string, else None."""
    from scripts.xfp.lib.triangulate_core import il_caveat
    assert il_caveat('IL60') and 'ON IL' in il_caveat('IL60')
    assert il_caveat('IL10').startswith('🏥')
    assert il_caveat('SIXTY_DAY_DL') is not None
    assert il_caveat(None) is None
    assert il_caveat('ACTIVE') is None


def test_triangulate_il_status_surfaces_caveat():
    """An injured player rates elite on talent (model+archetype), so without an
    IL caveat triangulate would surface a naked BUY. Injecting il_status marks
    it without rewriting the talent verdict."""
    from scripts.xfp.lib.triangulate_core import triangulate_player
    base = triangulate_player('Aaron Judge')
    assert base['il_status'] is None
    assert '🏥' not in base['verdict']

    inj = triangulate_player('Aaron Judge', il_status='IL60')
    assert inj['il_status'] == 'IL60'
    assert '🏥 ON IL' in inj['verdict']
    assert inj['override_tag'] and 'IL' in inj['override_tag']
    # the underlying talent read is preserved, just caveated
    assert base['verdict'] in inj['verdict']


def test_unknown_player_returns_none():
    """Names that don't resolve to any bucket must return None, not raise."""
    assert triangulate_player("Not A Real Player") is None
    assert triangulate_player("") is None


def test_parker_messick_unresolved():
    """Rookie SP without archetype/projection coverage — locks current
    behavior. If he later gets added to the panels this will flip to
    a real verdict and the test should be updated."""
    # We don't enforce None here forever; just lock current behavior.
    result = triangulate_player("Parker Messick")
    if result is not None:
        assert result["bucket"] in ("SP", "H", "RP")


def test_all_verdict_tiers_known():
    """The verdict map must enumerate every tier the engine can emit.
    If a new tier is added without updating _VERDICT_MAP it will fall
    through consolidate_verdict's prefix fallback and lose its reason tag.
    2026-06-14: added 'CAUTION — decline veto' (the SP velo-decline veto).
    """
    expected_tiers = {
        "STRONG HOLD/BUY",
        "BUY — archetype breakout",
        "BUY — model anchored on prior",
        "BUY — process upgrade",
        "BUY — under-the-radar",
        "BUY — outcomes only (no archetype)",
        "HOLD — post-TJ ramp candidate",
        "HOLD — process intact",
        "CAUTION — decline veto",
        "CAUTION",
        "FADE — PL chasing outcomes",
        "MIXED — see profile",
    }
    actual = set(_VERDICT_MAP.keys())
    assert actual == expected_tiers, (
        f"Verdict tier set drifted. Added: {actual - expected_tiers}. "
        f"Removed: {expected_tiers - actual}."
    )
    assert len(_VERDICT_MAP) == 12


@pytest.mark.parametrize("tier", list(_VERDICT_MAP.keys()))
def test_consolidate_verdict_round_trips(tier):
    """Every known tier must consolidate to a non-'unknown' reason tag."""
    verdict_top, reason_tag = consolidate_verdict(tier)
    assert verdict_top in ("BUY", "HOLD", "CAUTION", "FADE", "MIXED")
    assert reason_tag != "unknown"


def test_result_dict_has_csv_columns():
    """The triangulate_player return dict must expose every key that
    run_triangulate.py writes to the batch CSV. Catches schema drift
    that would break the dashboard pipeline."""
    expected_keys = {
        "player", "bucket",
        "pl_main", "pl_main_date",
        "pl_stream", "pl_stream_opp", "pl_stream_date",
        "pl_rank", "model_rank", "model_proj",
        "arche_overall", "arche_label", "arche_traj",
        "model", "arche",
        "verdict", "verdict_top", "reason_tag",
        "confidence", "confidence_n_aligned", "confidence_n_available",
        "watch_list", "rationale", "override_tag",
    }
    result = triangulate_player("Aaron Judge")
    assert result is not None
    missing = expected_keys - set(result.keys())
    assert not missing, f"triangulate_player() missing keys: {missing}"


def test_lru_cache_avoids_redundant_disk_reads():
    """Calling triangulate_player twice on the same bucket must not
    re-read the projection parquet/CSV from disk."""
    # Prime
    triangulate_player("Aaron Judge")
    info_before = _load_projection.cache_info()
    # Same bucket
    triangulate_player("Trea Turner")
    info_after_same = _load_projection.cache_info()
    assert info_after_same.misses == info_before.misses, (
        "Same-bucket second call caused additional cache miss "
        f"(misses {info_before.misses} -> {info_after_same.misses})"
    )
    # Hits should be strictly increasing across calls
    assert info_after_same.hits >= info_before.hits


def test_override_tag_none_for_non_overridden_verdicts():
    """Non-overridden verdicts must never carry an override tag. The HOLD/
    DECLINE_VETO overrides only fire on their specific triggers (bearish
    starting verdict for the HOLD overrides; SP BUY + SEVERE/DECLINE-RISK
    for the decline veto). A plain MIXED/BUY with neither must passthrough."""
    # Aaron Judge -> currently MIXED (2026-06-14 drift); never overridden.
    r = triangulate_player("Aaron Judge")
    assert r is not None and r["verdict_top"] in ("BUY", "MIXED")
    assert r["override_tag"] is None

    # Synthetic: a BUY with NO decline signals (no velo_severity/decline_tier)
    # must passthrough untouched.
    player = {"bucket": "SP"}
    arche = {"have": True, "career_year": 5, "career_pct": 0.0,
             "archetype": "WILD_MID", "traj_flag": "CAREER_LOW",
             "sub_ratings": {"SWING_MISS": 70, "WALK_AVOID": 40}}
    model = {"rank": 10}
    v, r_, tag = apply_overrides("BUY — archetype breakout", "...", player, arche, model)
    assert v == "BUY — archetype breakout"
    assert tag is None

    # Synthetic: the SAME BUY but WITH a SEVERE velo fade must be vetoed.
    model_veto = {"rank": 10, "velo_severity": "SEVERE", "decline_tier": "STABLE"}
    v2, _, tag2 = apply_overrides("BUY — archetype breakout", "...", player, arche, model_veto)
    assert v2 == "CAUTION — decline veto"
    assert tag2 == "DECLINE_VETO"


def test_confidence_in_range():
    """Confidence must be in [0, 1] for every canonical case."""
    for case in CANONICAL_CASES:
        name = case[0]
        r = triangulate_player(name)
        if r is None:
            continue
        c = r["confidence"]
        assert 0.0 <= c <= 1.0, f"{name!r} confidence {c} out of [0,1]"
        assert r["confidence_n_aligned"] <= r["confidence_n_available"]


def test_watch_list_capped_at_five():
    """build_watch_list must return at most 5 triggers."""
    for case in CANONICAL_CASES[:6]:
        r = triangulate_player(case[0])
        if r is None:
            continue
        assert isinstance(r["watch_list"], list)
        assert len(r["watch_list"]) <= 5


@pytest.mark.slow
def test_batch_smoke():
    """Slow: exercise every canonical case end-to-end in one pass."""
    n_resolved = 0
    for case in CANONICAL_CASES:
        r = triangulate_player(case[0])
        if r is not None:
            n_resolved += 1
    assert n_resolved >= len(CANONICAL_CASES) - 1


def test_flatten_lenses_full_and_none_safe():
    """flatten_lenses serializes the nested context-only lenses into flat batch
    columns, rounds floats, and is None-safe when a lens is absent."""
    from scripts.xfp.lib.triangulate_core import flatten_lenses
    model = {
        'splits': {'rate_vs_L': 0.275123, 'rate_vs_R': 0.357987,
                   'lift_vs_L_pct': -12.345, 'lift_vs_R_pct': 8.9,
                   'pa_vs_L': 60, 'pa_vs_R': 180, 'dominant_side': 'R'},
        'expected': {'xwoba': 0.341111, 'woba': 0.366, 'gap': 0.024889,
                     'regression': 'OVERPERFORMING'},
        'expected_splits': {
            'vs_L': {'xwoba': 0.31, 'woba': 0.30, 'regression': 'ALIGNED', 'pa': 55},
            'vs_R': None},
        'home_away': {'rate_home': 0.36, 'rate_away': 0.33, 'lift_home_pct': 4.4,
                      'lift_away_pct': -4.4, 'dominant_side': 'HOME'},
        'tto_decay': {'tier': 'DECAY', 'penalty': -0.0612,
                      'tto1_rate': 0.12, 'tto3_rate': 0.0588},
    }
    f = flatten_lenses(model, 'SP')
    assert f['split_rate_vs_L'] == 0.275 and f['split_dominant'] == 'R'
    assert f['split_lift_vs_L_pct'] == -12.3      # 1-dp rounding
    assert f['xstat_regression'] == 'OVERPERFORMING' and f['xstat_gap'] == 0.025
    assert f['xstat_vs_L_reg'] == 'ALIGNED' and f['xstat_vs_L_pa'] == 55
    assert f['xstat_vs_R_xwoba'] is None and f['xstat_vs_R_reg'] is None
    assert f['ha_dominant'] == 'HOME' and f['ha_rate_home'] == 0.36
    assert f['tto_tier'] == 'DECAY' and f['tto_penalty'] == -0.061

    # absent lenses -> all keys present, all None (schema-stable for CSV)
    empty = flatten_lenses({}, 'H')
    assert empty['split_rate_vs_L'] is None and empty['tto_tier'] is None
    assert set(empty) == set(f), "column schema must be bucket-independent"


def test_flatten_actuals_full_and_none_safe():
    """flatten_actuals serializes boom/bust + in-season trajectory into flat batch
    columns (compact deltas), and is schema-stable / None-safe when absent."""
    from scripts.xfp.lib.triangulate_core import flatten_actuals
    act = {
        'boom_window': 'L8 starts',
        'boom_bust': {'n': 8, 'mean': 14.9, 'std': 11.6, 'min': -9.1, 'max': 24.4,
                      'boom_pct': 50, 'bust_pct': 12, 'l3_mean': 20.0, 'trend': 'UP',
                      'last': [22.8, 9.0, 24.4, -9.1]},
        'trajectory': {
            'domains': ('STUFF', 'MOVEMENT', 'CONTROL'), 'xkey': 'start_no',
            'points': [
                {'label': '#3', 'OVERALL': 54, 'STUFF': 60, 'MOVEMENT': 50, 'CONTROL': 45,
                 'archetype': 'PURE_STUFF'},
                {'label': '#16', 'OVERALL': 48, 'STUFF': 54, 'MOVEMENT': 56, 'CONTROL': 52,
                 'archetype': 'AVERAGE_4_5'},
            ]},
    }
    f = flatten_actuals(act)
    assert f['bb_window'] == 'L8 starts' and f['bb_n'] == 8 and f['bb_mean'] == 14.9
    assert f['bb_boom_pct'] == 50 and f['bb_bust_pct'] == 12 and f['bb_trend'] == 'UP'
    assert f['bb_last'] == '22.8 9.0 24.4 -9.1'
    assert f['traj_n'] == 2 and f['traj_cadence'] == 'per_start'
    assert f['traj_ovr_first'] == 54 and f['traj_ovr_last'] == 48 and f['traj_ovr_delta'] == -6
    assert f['traj_last_archetype'] == 'AVERAGE_4_5'
    # per-domain first->last deltas, compact and signed
    assert f['traj_dom_deltas'] == 'STUFF:-6;MOVEMENT:+6;CONTROL:+7'
    # most-recent snapshot's domain values (Stuff/Movement/Control here)
    assert f['traj_dom_last'] == 'STUFF=54;MOVEMENT=56;CONTROL=52'

    empty = flatten_actuals(None)
    assert empty['bb_n'] is None and empty['traj_ovr_delta'] is None
    assert set(empty) == set(f), "actuals column schema must be stable"


def test_flatten_extra_full_and_none_safe():
    """flatten_extra serializes the 4 validated context lenses (Stuff+ / floor /
    trend / shadow) into stable flat columns, None-safe when absent."""
    from scripts.xfp.lib.triangulate_core import flatten_extra
    model = {
        'stuff': {'stuff_plus': 104.6, 'proj_ros_fp': 12.38, 'breakout_gap': 39, 'stuff_pctl': 76},
        'floor': {'bust_prob': 28, 'tier': 'MODERATE'},
        'trend': {'tag': '🔺 breakout watch'},
        'shadow': {'avg_grade': 59, 'verdict': 'AVG_PROCESS', 'grades': {'fb_velo': 30}},
    }
    f = flatten_extra(model, 'SP')
    assert f['stuff_plus'] == 104.6 and f['stuff_breakout_gap'] == 39
    assert f['floor_tier'] == 'MODERATE' and f['floor_bust_prob'] == 28
    assert f['trend_tag'] == '🔺 breakout watch'
    assert f['shadow_grade'] == 59 and f['shadow_verdict'] == 'AVG_PROCESS'
    empty = flatten_extra({}, 'H')
    assert empty['stuff_plus'] is None and empty['floor_tier'] is None and empty['trend_tag'] is None
    assert set(empty) == set(f), "extra-lens column schema must be stable"
