"""
PLPlvModel -- run-value-based approximation of Pitcher List's PLV and PLA metrics.

Methodology: aggregate mean(-delta_run_exp) per pitcher, then apply an OLS-fitted
affine transform to match Pitcher List's published scale (~5.0 mean, ~0.15 std for PLV).
PLA uses a separate affine transform. Per-pitch-type scores use 8 independent transforms.

rv_method options:
  "plv_components" -- OLS on 7 model-probability features from plv_scores (best; r~0.85)
  "plv_raw"        -- single plv_raw feature from plv_scores (r~0.50)
  "delta_run_exp"  -- raw Statcast run-expectancy change from pitch_features (r~0.33)
  "xwoba_blend"    -- delta_run_exp with xwOBA substituted for BIP (r~0.35)

plv_components gives the best out-of-sample correlation with PL's published PLV by
combining our LightGBM model's predicted probabilities (p_swing, p_cs_given_take, etc.)
via OLS linear regression. Requires plv_scores parquet (not pitch_features).

This model is intentionally simple (no LightGBM). Scaling params are fit once against
a reference season (2025) and stored as JSON.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd
from scipy.stats import linregress, pearsonr

from plv_clone.utils.io import read_json, write_json

# Statcast pitch_type -> PL's 8 standard types (None = drop)
_PT_MAP: dict[str, str | None] = {
    "FF": "FF",
    "FA": None,   # generic fastball -- too ambiguous
    "FT": "SI",   # 2-seam maps to sinker
    "SI": "SI",
    "SL": "SL",
    "ST": "ST",   # sweeper (2023+)
    "SV": "SL",   # slurve -> slider
    "CH": "CH",
    "CU": "CU",
    "KC": "CU",   # knuckle-curve
    "FC": "FC",
    "FS": "FS",
    "EP": None,
    "KN": None,
    "PO": None,
    "SC": None,
}

PT_COLS = ["FF", "SI", "SL", "ST", "CH", "CU", "FC", "FS"]

# 7 model-probability features used for plv_components method
COMPONENT_FEATS = [
    "plv_raw",
    "p_swing",
    "p_cs_given_take",
    "p_whiff_given_swing",
    "p_contact_given_swing",
    "p_in_play_given_contact",
    "e_xwoba_in_play",
]

_DEFAULT_MIN_PT = 10      # minimum per-pitcher pitch-type occurrences to report a score
_FALLBACK_MIN_PAIRS = 20  # minimum pitcher-type pairs needed to fit per-type OLS


class PLPlvModel:
    """Run-value-based PLV/PLA model approximating Pitcher List's methodology."""

    def __init__(self, scaling_params: dict | None = None) -> None:
        self.scaling_params: dict = scaling_params or {}

    # -- Pitch-level scoring ---------------------------------------------------

    def score_pitches(self, pitch_df: pd.DataFrame) -> pd.DataFrame:
        """Add pitch_plv_raw and pitch_pla_raw columns.

        pitch_plv_raw = value of pitch for the pitcher (higher = better).
        pitch_pla_raw = value generated by the batter (higher = worse for pitcher).

        For rv_method="plv_components": applies stored component_weights as a
        weighted linear combination of 7 probability columns. Requires plv_scores.
        """
        df = pitch_df.copy()
        rv_method = self.scaling_params.get("rv_method", "delta_run_exp")

        if rv_method == "plv_components":
            cw = self.scaling_params.get("component_weights")
            if not cw:
                raise ValueError(
                    "rv_method='plv_components' requires component_weights. "
                    "Run fit_scaling() or load a trained model first."
                )
            missing = [c for c in COMPONENT_FEATS if c not in df.columns]
            if missing:
                raise ValueError(
                    f"rv_method='plv_components' requires columns: {missing}. "
                    "Load from plv_scores/ instead of pitch_features/."
                )
            pitch_plv_raw = sum(
                float(cw.get(feat, 0.0)) * df[feat].fillna(0.0)
                for feat in COMPONENT_FEATS
            )
            # PLA uses separate OLS weights
            pla_cw = self.scaling_params.get("pla_component_weights", cw)
            pitch_pla_raw = sum(
                float(pla_cw.get(feat, 0.0)) * df[feat].fillna(0.0)
                for feat in COMPONENT_FEATS
            )

        elif rv_method == "plv_raw":
            if "plv_raw" not in df.columns:
                raise ValueError(
                    "rv_method='plv_raw' requires a 'plv_raw' column. "
                    "Load from plv_scores/ instead of pitch_features/."
                )
            pitch_plv_raw = df["plv_raw"].fillna(0.0)
            pitch_pla_raw = -pitch_plv_raw

        else:
            # Base: negate delta_run_exp so positive = good for pitcher
            pitch_plv_raw = -df["delta_run_exp"].fillna(0.0)

            if rv_method == "xwoba_blend":
                xwoba_scale = float(self.scaling_params.get("xwoba_scale", 0.32))
                is_ip_col = df.get("is_in_play", pd.Series(False, index=df.index))
                is_ip = is_ip_col.astype(bool)
                xwoba = df.get(
                    "estimated_woba_using_speedangle",
                    pd.Series(np.nan, index=df.index),
                )
                ip_val = -xwoba.fillna(0.0) * xwoba_scale
                pitch_plv_raw = pitch_plv_raw.where(~is_ip, ip_val)

            pitch_pla_raw = -pitch_plv_raw

        df["pitch_plv_raw"] = pitch_plv_raw
        df["pitch_pla_raw"] = pitch_pla_raw
        return df

    # -- Pitcher-level aggregation --------------------------------------------

    def aggregate(
        self,
        scored_df: pd.DataFrame,
        min_pitches: int = 200,
        year: int | None = None,
    ) -> pd.DataFrame:
        """Aggregate pitch-level scores to a pitcher-level leaderboard DataFrame.

        Columns: pitcher, pitcher_name, [year], num_pitches, pl_plv, pl_pla,
                 pl_plv_FF, pl_plv_SI, ..., pl_plv_FS
        """
        name_col = "player_name" if "player_name" in scored_df.columns else "pitcher_name"

        # -- Pitcher-level aggregation ----------------------------------------
        grp = scored_df.groupby(["pitcher", name_col], sort=False)
        agg = grp.agg(
            num_pitches=("pitch_plv_raw", "count"),
            rv_mean=("pitch_plv_raw", "mean"),
            pla_mean=("pitch_pla_raw", "mean"),
        ).reset_index()

        agg = agg[agg["num_pitches"] >= min_pitches].copy()

        plv_slope = self.scaling_params.get("plv_slope", 1.0)
        plv_intercept = self.scaling_params.get("plv_intercept", 5.0)
        agg["pl_plv"] = plv_slope * agg["rv_mean"] + plv_intercept

        pla_slope = self.scaling_params.get("pla_slope", 1.0)
        pla_intercept = self.scaling_params.get("pla_intercept", 3.5)
        agg["pl_pla"] = pla_slope * agg["pla_mean"] + pla_intercept

        # For plv_components, rv_mean and pla_mean already encode the OLS combination,
        # so plv_slope=1.0 and plv_intercept=b0 give the correct PLV/PLA directly.

        # -- Per-pitch-type ---------------------------------------------------
        pt_slopes: dict = self.scaling_params.get("pt_slopes", {})
        pt_intercepts: dict = self.scaling_params.get("pt_intercepts", {})
        min_pt: int = self.scaling_params.get("min_pitches_pt", _DEFAULT_MIN_PT)

        scored_mapped = scored_df.assign(pitch_type_pl=_map_pitch_types(scored_df))
        pt_grp = scored_mapped.groupby(["pitcher", "pitch_type_pl"], sort=False)
        pt_agg = pt_grp.agg(
            pt_count=("pitch_plv_raw", "count"),
            pt_rv_mean=("pitch_plv_raw", "mean"),
        ).reset_index()
        pt_agg = pt_agg[
            pt_agg["pitch_type_pl"].notna()
            & (pt_agg["pt_count"] >= min_pt)
            & pt_agg["pitch_type_pl"].isin(PT_COLS)
        ].copy()

        pt_agg["pt_plv"] = np.nan
        for pt in PT_COLS:
            mask = pt_agg["pitch_type_pl"] == pt
            if mask.any():
                s = pt_slopes.get(pt, plv_slope)
                i = pt_intercepts.get(pt, plv_intercept)
                pt_agg.loc[mask, "pt_plv"] = s * pt_agg.loc[mask, "pt_rv_mean"] + i

        if not pt_agg.empty:
            pt_wide = pt_agg.pivot_table(
                index="pitcher",
                columns="pitch_type_pl",
                values="pt_plv",
                aggfunc="first",
            )
            pt_wide.columns = [f"pl_plv_{c}" for c in pt_wide.columns]
            pt_wide = pt_wide.reset_index()
        else:
            pt_wide = pd.DataFrame({"pitcher": pd.Series(dtype="int64")})

        for col in [f"pl_plv_{pt}" for pt in PT_COLS]:
            if col not in pt_wide.columns:
                pt_wide[col] = np.nan

        agg = agg.merge(pt_wide, on="pitcher", how="left")
        agg = agg.rename(columns={name_col: "pitcher_name"})
        if year is not None:
            agg["year"] = year

        col_order = (
            ["pitcher", "pitcher_name"]
            + (["year"] if year is not None else [])
            + ["num_pitches", "pl_plv", "pl_pla"]
            + [f"pl_plv_{pt}" for pt in PT_COLS]
        )
        return (
            agg[[c for c in col_order if c in agg.columns]]
            .sort_values("pl_plv", ascending=False)
            .reset_index(drop=True)
        )

    # -- Scaling fit ----------------------------------------------------------

    def fit_scaling(
        self,
        pitch_df: pd.DataFrame,
        ref_df: pd.DataFrame,
        rv_method: str = "delta_run_exp",
        xwoba_scale: float | None = None,
    ) -> float:
        """Fit OLS normalization params against reference data. Returns Pearson r(PLV)."""
        self.scaling_params["rv_method"] = rv_method
        if xwoba_scale is not None:
            self.scaling_params["xwoba_scale"] = float(xwoba_scale)

        ref_clean = _clean_ref(ref_df)

        if rv_method == "plv_components":
            return self._fit_components(pitch_df, ref_clean)

        # -- Standard (single-signal) methods ----------------------------------
        scored = self.score_pitches(pitch_df)
        grp = scored.groupby("pitcher", sort=False)
        pit_stats = grp.agg(
            num_pitches=("pitch_plv_raw", "count"),
            rv_mean=("pitch_plv_raw", "mean"),
            pla_mean=("pitch_pla_raw", "mean"),
        ).reset_index()

        merged = pit_stats.merge(ref_clean, on="pitcher", how="inner")
        if merged.empty:
            raise ValueError(
                "No pitchers matched between pitch features and reference CSV. "
                "Check that pitcher MLBAM IDs align."
            )

        # PLV OLS: rv_mean (positive = good pitcher) -> PLV (higher = better)
        r_plv = linregress(merged["rv_mean"], merged["PLV"])
        self.scaling_params["plv_slope"] = float(r_plv.slope)
        self.scaling_params["plv_intercept"] = float(r_plv.intercept)

        # PLA OLS: pla_mean = -rv_mean -> PLA (lower = better; positive slope)
        merged["pla_mean"] = -merged["rv_mean"]
        r_pla = linregress(merged["pla_mean"], merged["PLA"])
        self.scaling_params["pla_slope"] = float(r_pla.slope)
        self.scaling_params["pla_intercept"] = float(r_pla.intercept)

        # Per-pitch-type OLS
        self._fit_per_type(scored, ref_clean)
        self.scaling_params["min_pitches_pt"] = _DEFAULT_MIN_PT

        return float(r_plv.rvalue)

    def _fit_components(self, pitch_df: pd.DataFrame, ref_clean: pd.DataFrame) -> float:
        """OLS regression using 7 model-probability features -> PLV / PLA."""
        missing = [c for c in COMPONENT_FEATS if c not in pitch_df.columns]
        if missing:
            raise ValueError(
                f"rv_method='plv_components' requires columns {missing}. "
                "Pass plv_scores data (not pitch_features)."
            )

        # Pitcher-level means of each component
        comp_agg = (
            pitch_df.groupby("pitcher")[COMPONENT_FEATS]
            .mean()
            .reset_index()
        )
        merged = comp_agg.merge(ref_clean, on="pitcher", how="inner")
        if merged.empty:
            raise ValueError("No pitchers matched. Check MLBAM IDs.")

        X = merged[COMPONENT_FEATS].values.astype(float)
        X2 = np.column_stack([X, np.ones(len(X))])

        # PLV OLS
        b_plv, *_ = np.linalg.lstsq(X2, merged["PLV"].values, rcond=None)
        self.scaling_params["component_weights"] = dict(
            zip(COMPONENT_FEATS, [float(v) for v in b_plv[:-1]])
        )
        self.scaling_params["plv_slope"] = 1.0
        self.scaling_params["plv_intercept"] = float(b_plv[-1])

        # PLA OLS
        b_pla, *_ = np.linalg.lstsq(X2, merged["PLA"].values, rcond=None)
        self.scaling_params["pla_component_weights"] = dict(
            zip(COMPONENT_FEATS, [float(v) for v in b_pla[:-1]])
        )
        self.scaling_params["pla_slope"] = 1.0
        self.scaling_params["pla_intercept"] = float(b_pla[-1])

        # Per-pitch-type OLS (now that component_weights are set, score_pitches works)
        scored = self.score_pitches(pitch_df)
        self._fit_per_type(scored, ref_clean)
        self.scaling_params["min_pitches_pt"] = _DEFAULT_MIN_PT

        pred_plv = X2 @ b_plv
        r_plv, _ = pearsonr(pred_plv, merged["PLV"].values)
        return float(r_plv)

    def _fit_per_type(self, scored: pd.DataFrame, ref_clean: pd.DataFrame) -> None:
        """Fit per-pitch-type OLS transforms. Updates scaling_params in-place."""
        plv_slope = self.scaling_params.get("plv_slope", 1.0)
        plv_intercept = self.scaling_params.get("plv_intercept", 5.0)

        scored_mapped = scored.assign(pitch_type_pl=_map_pitch_types(scored))
        pt_grp = scored_mapped.groupby(["pitcher", "pitch_type_pl"], sort=False)
        pt_agg = pt_grp.agg(
            pt_count=("pitch_plv_raw", "count"),
            pt_rv_mean=("pitch_plv_raw", "mean"),
        ).reset_index()
        pt_agg = pt_agg[
            pt_agg["pitch_type_pl"].notna()
            & (pt_agg["pt_count"] >= _DEFAULT_MIN_PT)
            & pt_agg["pitch_type_pl"].isin(PT_COLS)
        ]

        pt_slopes: dict[str, float] = {}
        pt_intercepts: dict[str, float] = {}
        for pt in PT_COLS:
            if pt not in ref_clean.columns:
                continue
            pt_sub = pt_agg[pt_agg["pitch_type_pl"] == pt].merge(
                ref_clean[["pitcher", pt]].dropna(subset=[pt]),
                on="pitcher",
                how="inner",
            )
            if len(pt_sub) < _FALLBACK_MIN_PAIRS:
                continue
            res = linregress(pt_sub["pt_rv_mean"], pt_sub[pt])
            pt_slopes[pt] = float(res.slope)
            pt_intercepts[pt] = float(res.intercept)

        self.scaling_params["pt_slopes"] = pt_slopes
        self.scaling_params["pt_intercepts"] = pt_intercepts

    # -- Persistence ----------------------------------------------------------

    def save(self, models_dir: Path) -> None:
        models_dir = Path(models_dir)
        models_dir.mkdir(parents=True, exist_ok=True)
        write_json(self.scaling_params, models_dir / "pl_plv_scaling.json")

    @classmethod
    def load(cls, models_dir: Path) -> "PLPlvModel":
        params = read_json(Path(models_dir) / "pl_plv_scaling.json")
        return cls(scaling_params=params)


# -- Module-level helpers -----------------------------------------------------

def _map_pitch_types(df: pd.DataFrame) -> pd.Series:
    """Map Statcast pitch_type codes to PL's 8-type set. Returns NaN for unknown/drop."""
    return df["pitch_type"].map(_PT_MAP)


def _clean_ref(ref_df: pd.DataFrame) -> pd.DataFrame:
    """Normalise reference DataFrame: rename MLBAMID->pitcher (int)."""
    df = ref_df.rename(columns={"MLBAMID": "pitcher"}).copy()
    df["pitcher"] = df["pitcher"].astype(int)
    return df


def load_and_clean_reference(ref_path: Path) -> pd.DataFrame:
    """Load a Pitcher List reference CSV and replace year-specific sentinel values with NaN.

    The sentinel is any value > 6.0 in pitch-type columns (varies by year).
    Using .where() handles floating-point near-duplicates uniformly.
    """
    df = pd.read_csv(ref_path)
    for col in PT_COLS:
        if col in df.columns:
            df[col] = df[col].where(df[col] <= 6.0, float("nan"))
    return df
